name: suite3d-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11, <3.13 # 3.8,<3.9
  - pip
  - mkl
  - tbb
  - cupy
  - numpy
  - napari
  - pyqt
  - pyqtgraph
  - numba
  - matplotlib
  - ipykernel
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - scikit-learn
  - mrcfile
  - panel
  - mkl_fft
  - dask-image
  - pip: 
    - scipy>=1.4.0
    - torch>=1.7.1
    - natsort
    - rastermap>0.1.0
    - tifffile>=2021.3.4
    - scanimage-tiff-reader>=1.4.1
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - imreg-dft-nw
