name: Install and Test Suite3D

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  test-full:
    if: >
      startsWith(github.event.head_commit.message, 'ci')
    name: Tests
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11",]  # ["3.12", "3.13"]
        os: ["ubuntu-latest",] # "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python }} #"3.11"}
          enable-cache: true

      - name: Sync dependencies
        run: uv lock --upgrade && uv sync
